select SERVICE_DEPTS.NAME from SERVICE_DEPTS
where SERVICE_DEPTS.DEPT_CODE in (
    select DEPT_HAS_BODY_PART.DEPT_CODE from DEPT_HAS_BODY_PART
    where DEPT_HAS_BODY_PART.BODY_CODE in (
        select SYM_HAS_BODY_PART.BODY_CODE from SYMPTOMS, SYM_HAS_BODY_PART
        where SYMPTOMS.SYM_CODE = SYM_HAS_BODY_PART.SYM_CODE and SYMPTOMS.NAME = 'Blurred vision'
    )
);
/

select * from (select H1.NAME, count(H1.IS_MEDICAL) from (
    (select MEDICAL_FACILITIES.NAME, STAFFS.EMPLOYEE_ID, STAFFS.IS_MEDICAL from
    STAFFS, MEDICAL_FACILITIES, FACILITY_HAS_DEPT where
    STAFFS.IS_MEDICAL = 1 and
    STAFFS.PRIMARY_DEPT_CODE = FACILITY_HAS_DEPT.DEPT_CODE and
    MEDICAL_FACILITIES.FACILITY_ID = FACILITY_HAS_DEPT.FACILITY_ID)
    union
    (select MEDICAL_FACILITIES.NAME, STAFFS.EMPLOYEE_ID, STAFFS.IS_MEDICAL from
    STAFFS,MEDICAL_FACILITIES, FACILITY_HAS_DEPT, STAFF_SECO_WORKS_DEPT where
    STAFFS.IS_MEDICAL = 1 and
    STAFFS.EMPLOYEE_ID = STAFF_SECO_WORKS_DEPT.EMPLOYEE_ID and
    STAFF_SECO_WORKS_DEPT.DEPT_CODE = FACILITY_HAS_DEPT.DEPT_CODE and
    MEDICAL_FACILITIES.FACILITY_ID = FACILITY_HAS_DEPT.FACILITY_ID)
) H1
group by H1.NAME) J1
/

select * from (select H2.NAME, count(H2.IS_MEDICAL) from (
    (select MEDICAL_FACILITIES.NAME, STAFFS.EMPLOYEE_ID, STAFFS.IS_MEDICAL from
    STAFFS, MEDICAL_FACILITIES, FACILITY_HAS_DEPT where
    STAFFS.IS_MEDICAL = 0 and
    STAFFS.PRIMARY_DEPT_CODE = FACILITY_HAS_DEPT.DEPT_CODE and
    MEDICAL_FACILITIES.FACILITY_ID = FACILITY_HAS_DEPT.FACILITY_ID)
    union
    (select MEDICAL_FACILITIES.NAME, STAFFS.EMPLOYEE_ID, STAFFS.IS_MEDICAL from
    STAFFS,MEDICAL_FACILITIES, FACILITY_HAS_DEPT, STAFF_SECO_WORKS_DEPT where
    STAFFS.IS_MEDICAL = 0 and
    STAFFS.EMPLOYEE_ID = STAFF_SECO_WORKS_DEPT.EMPLOYEE_ID and
    STAFF_SECO_WORKS_DEPT.DEPT_CODE = FACILITY_HAS_DEPT.DEPT_CODE and
    MEDICAL_FACILITIES.FACILITY_ID = FACILITY_HAS_DEPT.FACILITY_ID)
) H2
group by H2.NAME) J2

/
